version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      |
         export DEBIAN_FRONTEND=noninteractive
         #Install php7.1
         apt-get update
         apt-get install -y  software-properties-common
         LC_ALL=C.UTF-8 add-apt-repository -y ppa:ondrej/php
         apt-get update
         # Install PHP
         apt-get install -y php
                  php-ldap \
                  php-xml \
                  php-xmlrpc \
                  php-zip \
                  php-mysql \
                  php-mbstring \
                  php-mcrypt \
                  php-gd \
                  php-readline \
                  php-opcache \
                  php-xdebug \
                  php-dom \
                  php-xdebug \
                  php-curl \
                  unzip
         #Enable xdebug - phpunit uses this for code coverage
         phpenmod xdebug
         #Install composer
         php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
         php composer-setup.php ;
         php -r "unlink('composer-setup.php');" ;
         mv composer.phar /usr/local/bin/composer
  pre_build:
    commands:
      - echo "Entered the pre_build phase..."
  build:
    commands:
      - composer install --no-progress --no-suggest
      - echo "Build started on `date`"
  post_build:
    commands:
      - echo "Entered the post_build phase..."
      - echo "Build completed on `date`"

artifacts:
  files:
    - '**/*'
  name: my-webapp-artifact 
