version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      |
         export DEBIAN_FRONTEND=noninteractive
         apt-get update
         apt-get install -y php php-curl php-zip php-dom php-xml php-gd composer
  pre_build:
    commands:
      - echo "Entered the pre_build phase..."
  build:
    commands:
      - echo "Build started on `date`"
      - composer install
  post_build:
    commands:
      - echo "Entered the post_build phase..."
      - echo "Build completed on `date`"

artifacts:
  files:
    - '**/*'
  name: my-webapp-artifact 
